spring:
  datasource:
    url: jdbc:h2:file:./h2/testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

flyway:
  locations:classpath:db/migration
  baselineOnMigrate:true
server:
  port: 8081